export const Action = {
    RANDOM_CAT_FETCH_DATA_START     : 'RANDOM_CAT_FETCH_DATA_START',
    RANDOM_CAT_FETCH_DATA_COMPLETE  : 'RANDOM_CAT_FETCH_DATA_COMPLETE',
    RANDOM_CAT_FETCH_DATA_FAIL      : 'RANDOM_CAT_FETCH_DATA_FAIL',
    MIT_FETCH_DATA_START            : 'MIT_FETCH_DATA_START',
    MIT_FETCH_DATA_COMPLETE         : 'MIT_FETCH_DATA_COMPLETE',
    MIT_FETCH_DATA_FAIL             : 'MIT_FETCH_DATA_FAIL',
    UPDATE_LOCALE_DATA_START        : 'UPDATE_LOCALE_DATA_START',
    UPDATE_LOCALE_DATA_COMPLETE     : 'UPDATE_LOCALE_DATA_COMPLETE',
    UPDATE_LOCALE_DATA_FAIL         : 'UPDATE_LOCALE_DATA_FAIL',
    STATIC_FILE_FETCH_DATA_START    : 'STATIC_FILE_FETCH_DATA_START',
    STATIC_FILE_FETCH_DATA_COMPLETE : 'STATIC_FILE_FETCH_DATA_COMPLETE',
    STATIC_FILE_FETCH_DATA_FAIL     : 'STATIC_FILE_FETCH_DATA_FAIL',
};