export const Features = {
    ecma          : 'ecma',
    reactAndRedux : 'reactAndRedux',
    reactRouter   : 'reactRouter',
    webpack       : 'webpack',
    watch         : 'watch',
    restart       : 'restart',
    cssModules    : 'cssModules',
    manyLoaders   : 'manyLoaders',
    intl          : 'intl',
    fetchData     : 'fetchData',
    test          : 'test',
    coverage      : 'coverage',
    linter        : 'linter',
    flow          : 'flow',
    mit           : 'mit',
};